app_country_index:
    path: /country
    controller: App\Controller\CountryController::index
    methods: ['GET']

app_country_load:
    path: /load-countries
    controller: App\Controller\LoadController::loadCountries
    methods: ['GET']

    #app_country_delete_multiple:
    #path: /delete-multiple
    #controller: App\Controller\CountryDeleteController::deleteMultiple
    #methods: POST

controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

